//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagonoteToolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagonoteToolkit.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視対象追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFileChangeMonitorTarget {
            get {
                return ResourceManager.GetString("AddFileChangeMonitorTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック済みのタイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckedTimestamp {
            get {
                return ResourceManager.GetString("CheckedTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換ルールファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertRulesFilePath {
            get {
                return ResourceManager.GetString("ConvertRulesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のタイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentTimestamp {
            get {
                return ResourceManager.GetString("CurrentTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したものを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteSelectedItem {
            get {
                return ResourceManager.GetString("DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFile {
            get {
                return ResourceManager.GetString("ExaminationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFileKeyword {
            get {
                return ResourceManager.GetString("ExaminationFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationResult {
            get {
                return ResourceManager.GetString("ExaminationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationSettings {
            get {
                return ResourceManager.GetString("ExaminationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationTarget {
            get {
                return ResourceManager.GetString("ExaminationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excelファイル検査 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcelFileInspection {
            get {
                return ResourceManager.GetString("ExcelFileInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelファイルID-&gt;名称変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcelFileNumberToName {
            get {
                return ResourceManager.GetString("ExcelFileNumberToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteExamination {
            get {
                return ResourceManager.GetString("ExecuteExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteInspection {
            get {
                return ResourceManager.GetString("ExecuteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileChangeMonitor {
            get {
                return ResourceManager.GetString("FileChangeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileChangeMonitorResult {
            get {
                return ResourceManager.GetString("FileChangeMonitorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionFile {
            get {
                return ResourceManager.GetString("InspectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMethod {
            get {
                return ResourceManager.GetString("InspectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionResult {
            get {
                return ResourceManager.GetString("InspectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionSettings {
            get {
                return ResourceManager.GetString("InspectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用しているライブラリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル　もしくは　ファイルが含まれるフォルダを
        ///ドラッグ&amp;ドロップしてください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGuideDragAndDrop {
            get {
                return ResourceManager.GetString("MessageGuideDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細は以下のURLを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHelpFollowingURL {
            get {
                return ResourceManager.GetString("MessageHelpFollowingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MagonoteToolkitようこそへ!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody1 {
            get {
                return ResourceManager.GetString("MessageHomeBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションはソフトウェア開発を支援するツールキットです｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody2 {
            get {
                return ResourceManager.GetString("MessageHomeBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイドメニューからご希望の機能を選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody3 {
            get {
                return ResourceManager.GetString("MessageHomeBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題は見つかりませんでした｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionOK {
            get {
                return ResourceManager.GetString("MessageResultInspectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢調査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyExamination {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢検査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyInspection {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteExamination {
            get {
                return ResourceManager.GetString("MessageStatusCompleteExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteInspection {
            get {
                return ResourceManager.GetString("MessageStatusCompleteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を保存しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteSaveSettings {
            get {
                return ResourceManager.GetString("MessageStatusCompleteSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationTargetEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationTargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionMethodEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionMethodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査を行っています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowExamination {
            get {
                return ResourceManager.GetString("MessageStatusNowExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査を行っています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowInspection {
            get {
                return ResourceManager.GetString("MessageStatusNowInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Recheck {
            get {
                return ResourceManager.GetString("Recheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFilePath {
            get {
                return ResourceManager.GetString("SettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFileKeyword {
            get {
                return ResourceManager.GetString("TargetFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてタイムスタンプ更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTimestampAll {
            get {
                return ResourceManager.GetString("UpdateTimestampAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したものをタイムスタンプ更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTimestampSelectedItem {
            get {
                return ResourceManager.GetString("UpdateTimestampSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
    }
}
