//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagonoteToolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagonoteToolkit.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視対象追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFileChangeMonitorTarget {
            get {
                return ResourceManager.GetString("AddFileChangeMonitorTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI校正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AIProofreading {
            get {
                return ResourceManager.GetString("AIProofreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたはプロの校正者です。
        ///以下の【観点】で【校正対象】をチェックして､【出力形式】に沿って指摘の一覧と修正案を提示してください｡
        ///語彙や言い回しは変えないでください｡
        ///
        ///【観点】
        ///- 文法的な誤りがないこと｡
        ///- 取引先に対して不適切な表現がないこと｡
        ///- 表記の揺れがないこと｡
        ///- 誤字･脱字がないこと｡
        ///- 読みやすく､一度読んですぐ意味が伝わること｡
        ///- 一文が長すぎないこと｡
        ///- 無駄な表現を省き、短くまとめてあること｡
        ///- 一文一義になっていること｡
        ///- 敬語表現が適切であること｡
        ///- 主語や目的語は明確か､述語と近いところにあるか｡
        ///- 箇条書きや見出し､囲みなどを適切に使えているか｡
        ///- 二重否定を使っていないこと｡
        ///- 用語や表記、書式が全体で統一されていること｡
        ///- 読み手の操作は能動態で、結果は受動態で書いてあること｡
        ///
        ///【出力形式】
        ///=====指摘一覧=====
        ///指摘をMarkdownの表形式で出力(観点を番号のみで表現するのは不可)
        ///=====修正案=====
        ///修正案を出力(修正案の解説があると尚可)
        ///
        ///【校正対象】
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AIProofreadingDefaultPrompt {
            get {
                return ResourceManager.GetString("AIProofreadingDefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI関連 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AIRelated {
            get {
                return ResourceManager.GetString("AIRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI翻訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AITranslation {
            get {
                return ResourceManager.GetString("AITranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたはプロの翻訳家です。
        ///以下の【条件】で【翻訳対象】を{0}から{1}に翻訳してください｡
        ///
        ///【条件】
        ///- 直訳を避け、文脈に合った自然な表現にしてください。
        ///- 専門用語や固有名詞は適切に訳してください。
        ///- 翻訳文のみを出力し、余計な解説や前置きは書かないでください。
        ///- IT技術の専門用語を正確に反映し、エンジニアにとって自然な表現にしてください。
        ///
        ///【翻訳対象】
        ///{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AITranslationDefaultPrompt {
            get {
                return ResourceManager.GetString("AITranslationDefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   常に手前に表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CharCode {
            get {
                return ResourceManager.GetString("CharCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック済みのタイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckedTimestamp {
            get {
                return ResourceManager.GetString("CheckedTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードID-&gt;名称変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardNumberToName {
            get {
                return ResourceManager.GetString("ClipboardNumberToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボード文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardStrings {
            get {
                return ResourceManager.GetString("ClipboardStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertOption {
            get {
                return ResourceManager.GetString("ConvertOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換ルールファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertRulesFilePath {
            get {
                return ResourceManager.GetString("ConvertRulesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のタイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentTimestamp {
            get {
                return ResourceManager.GetString("CurrentTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したものを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteSelectedItem {
            get {
                return ResourceManager.GetString("DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFile {
            get {
                return ResourceManager.GetString("ExaminationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFileKeyword {
            get {
                return ResourceManager.GetString("ExaminationFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationResult {
            get {
                return ResourceManager.GetString("ExaminationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationSettings {
            get {
                return ResourceManager.GetString("ExaminationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationTarget {
            get {
                return ResourceManager.GetString("ExaminationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excelファイル検査 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcelFileInspection {
            get {
                return ResourceManager.GetString("ExcelFileInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelファイルID-&gt;名称変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExcelFileNumberToName {
            get {
                return ResourceManager.GetString("ExcelFileNumberToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑↑文字コード-&gt;文字列↑↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteConvertCharcodeToString {
            get {
                return ResourceManager.GetString("ExecuteConvertCharcodeToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓↓文字列-&gt;文字コード↓↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteConvertStringToCharcode {
            get {
                return ResourceManager.GetString("ExecuteConvertStringToCharcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteExamination {
            get {
                return ResourceManager.GetString("ExecuteExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteInspection {
            get {
                return ResourceManager.GetString("ExecuteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteProofreading {
            get {
                return ResourceManager.GetString("ExecuteProofreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteTranslation {
            get {
                return ResourceManager.GetString("ExecuteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileChangeMonitor {
            get {
                return ResourceManager.GetString("FileChangeMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変更監視結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileChangeMonitorResult {
            get {
                return ResourceManager.GetString("FileChangeMonitorResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペース名入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputWorkspaceName {
            get {
                return ResourceManager.GetString("InputWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionFile {
            get {
                return ResourceManager.GetString("InspectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionMethod {
            get {
                return ResourceManager.GetString("InspectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionResult {
            get {
                return ResourceManager.GetString("InspectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InspectionSettings {
            get {
                return ResourceManager.GetString("InspectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用しているライブラリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LibrariesUsed {
            get {
                return ResourceManager.GetString("LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本当に削除しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageConfirmDelete {
            get {
                return ResourceManager.GetString("MessageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル　もしくは　ファイルが含まれるフォルダを
        ///ドラッグ&amp;ドロップしてください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGuideDragAndDrop {
            get {
                return ResourceManager.GetString("MessageGuideDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細は以下のURLを参照してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHelpFollowingURL {
            get {
                return ResourceManager.GetString("MessageHelpFollowingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MagonoteToolkitようこそへ!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody1 {
            get {
                return ResourceManager.GetString("MessageHomeBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションはソフトウェア開発を支援するツールキットです｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody2 {
            get {
                return ResourceManager.GetString("MessageHomeBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイドメニューからご希望の機能を選択してください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageHomeBody3 {
            get {
                return ResourceManager.GetString("MessageHomeBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加するワークスペースの名前を入力してください｡(拡張子無し) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageInputWorkspaceName {
            get {
                return ResourceManager.GetString("MessageInputWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG：ファイルが見つかりません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultFileChangeMonitorNGNotFound {
            get {
                return ResourceManager.GetString("MessageResultFileChangeMonitorNGNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG：ファイルのタイムスタンプが一致しません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultFileChangeMonitorNGTimestampUnmatch {
            get {
                return ResourceManager.GetString("MessageResultFileChangeMonitorNGTimestampUnmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultFileChangeMonitorOK {
            get {
                return ResourceManager.GetString("MessageResultFileChangeMonitorOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルオープンエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultFileOpenError {
            get {
                return ResourceManager.GetString("MessageResultFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値に&quot;{0}&quot;が含まれています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGContains {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEmpty {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が&quot;{0}&quot;以外になっています｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGNotEqual {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が正規表現｢&quot;{0}&quot;｣にマッチします｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionNGRegex {
            get {
                return ResourceManager.GetString("MessageResultInspectionNGRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題は見つかりませんでした｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageResultInspectionOK {
            get {
                return ResourceManager.GetString("MessageResultInspectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢調査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyExamination {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢検査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyInspection {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteAdd {
            get {
                return ResourceManager.GetString("MessageStatusCompleteAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteCheck {
            get {
                return ResourceManager.GetString("MessageStatusCompleteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteDelete {
            get {
                return ResourceManager.GetString("MessageStatusCompleteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteExamination {
            get {
                return ResourceManager.GetString("MessageStatusCompleteExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteInspection {
            get {
                return ResourceManager.GetString("MessageStatusCompleteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteProcessing {
            get {
                return ResourceManager.GetString("MessageStatusCompleteProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を保存しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteSaveSettings {
            get {
                return ResourceManager.GetString("MessageStatusCompleteSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationTargetEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationTargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査方法が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInspectionMethodEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInspectionMethodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査を行っています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowExamination {
            get {
                return ResourceManager.GetString("MessageStatusNowExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査を行っています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowInspection {
            get {
                return ResourceManager.GetString("MessageStatusNowInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中です｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowProcessing {
            get {
                return ResourceManager.GetString("MessageStatusNowProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正を行っています｡
        ///しばらくお待ちください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowProofreading {
            get {
                return ResourceManager.GetString("MessageStatusNowProofreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳を行っています｡
        ///しばらくお待ちください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowTranslation {
            get {
                return ResourceManager.GetString("MessageStatusNowTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するモデル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelToBeUsed {
            get {
                return ResourceManager.GetString("ModelToBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenAI APIのベースURL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenAIAPIBaseUrl {
            get {
                return ResourceManager.GetString("OpenAIAPIBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenAI APIのAPIキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenAIAPIKey {
            get {
                return ResourceManager.GetString("OpenAIAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正プロンプトファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProofreadingPromptFilePath {
            get {
                return ResourceManager.GetString("ProofreadingPromptFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProofreadingResult {
            get {
                return ResourceManager.GetString("ProofreadingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正対象テキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProofreadingTargetText {
            get {
                return ResourceManager.GetString("ProofreadingTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Recheck {
            get {
                return ResourceManager.GetString("Recheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区切り文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeparatorChar {
            get {
                return ResourceManager.GetString("SeparatorChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFilePath {
            get {
                return ResourceManager.GetString("SettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列&lt;--&gt;文字コード変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCharcodeConvert {
            get {
                return ResourceManager.GetString("StringCharcodeConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFileKeyword {
            get {
                return ResourceManager.GetString("TargetFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳入力テキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslationInputText {
            get {
                return ResourceManager.GetString("TranslationInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳出力テキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslationOutputText {
            get {
                return ResourceManager.GetString("TranslationOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   翻訳プロンプトファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslationPromptFilePath {
            get {
                return ResourceManager.GetString("TranslationPromptFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてタイムスタンプ更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTimestampAll {
            get {
                return ResourceManager.GetString("UpdateTimestampAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したものをタイムスタンプ更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTimestampSelectedItem {
            get {
                return ResourceManager.GetString("UpdateTimestampSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペースディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WorkspaceDirectory {
            get {
                return ResourceManager.GetString("WorkspaceDirectory", resourceCulture);
            }
        }
    }
}
